[package]
name = "playbot_ng"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[dependencies]
serde = "1.0.25"
serde_derive = "1.0.25"
failure = "0.1.1"
irc = "0.12.6"
reqwest = "0.8.2"
