cargo-features = ["edition"]

[package]
name = "playbot_ng"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[lib]
name = "playbot"

[dependencies]
failure = "0.1.2"
reqwest = { version = "0.9.0-pre", git = "https://github.com/seanmonstar/reqwest", rev = "c328315" }
url = "1.7.1"
itertools = "0.7.8"
regex = "1.0.4"
lazy_static = "1.1.0"
playground = { path = "playground" }
cratesio = { path = "cratesio" }
futures-preview = "0.3.0-alpha.3"

[workspace]
members = [
    "playbot_irc",
    "reval",
]
