[package]
name = "playbot_ng"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[dependencies]
serde = "1.0.25"
serde_derive = "1.0.25"
failure = "0.1.1"
irc = "0.13.4"
reqwest = "0.8.2"
url = "1.6.0"
syn = { version = "0.11.11", features = ["full", "parsing", "printing"] }
serde_json = "1.0.9"
chrono = { version = "0.4.0", features = ["serde"] }
itertools = "0.7.7"
regex = "0.2.10"
