cargo-features = ["edition"]

[package]
name = "playbot_ng"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.2"
irc = { version = "0.13.5", git = "https://github.com/aatxe/irc", branch = "0.14" }
reqwest = "0.8.8"
url = "1.7.1"
serde_json = "1.0.26"
chrono = { version = "0.4.5", features = ["serde"] }
itertools = "0.7.8"
regex = "1.0.2"
lazy_static = "1.1.0"
playground = { path = "playground" }
cratesio = { path = "cratesio" }
serde_derive = "1.0.73"
serde = "1.0.73"
toml = "0.4.6"
futures-preview = { version = "0.3.0-alpha.3", features = ["tokio-compat"] }
tokio-core = "0.1.17"

[workspace]
