cargo-features = ["edition"]

[package]
name = "cratesio"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.8.8", features = ["unstable"] }
url = "1.7.1"
serde = "1.0.73"
serde_derive = "1.0.73"
futures-preview = { version = "0.3.0-alpha.3", features = ["tokio-compat"] }
tokio-core = "0.1.17"
